/* Server Version: WI-V6.0.1.0.  ODS Version: 10.0. */

SET SQL DIALECT 3;

CONNECT 'C:\Anglo\ANGLO_2005.GDB' USER 'SYSDBA' PASSWORD 'abc';

SET AUTODDL ON;

/* Drop: ALTER TABLE ALUNOS ADD CONSTRAINT FK_UF_CARTORIO FOREIGN KEY (UF_CARTORIO) REFERENCES ESTADO(COD_ESTADO) ON UPDATE CASCADE; */
ALTER TABLE ALUNOS DROP CONSTRAINT FK_UF_CARTORIO;
CONNECT 'C:\Anglo\ANGLO_2005.GDB' USER 'SYSDBA' PASSWORD 'abc';
/* Drop: ALTER TABLE ALUNOS ADD CONSTRAINT FK_NASCI_BRASIL FOREIGN KEY (UF_NACIONALIDADE_BRASIL) REFERENCES ESTADO(COD_ESTADO) ON UPDATE CASCADE; */
ALTER TABLE ALUNOS DROP CONSTRAINT FK_NASCI_BRASIL;
CONNECT 'C:\Anglo\ANGLO_2005.GDB' USER 'SYSDBA' PASSWORD 'abc';
/* Drop: ALTER TABLE ALUNOS ADD CONSTRAINT FK_MUN_NASC FOREIGN KEY (MUNICIPIO_NASC) REFERENCES MUNICIPIO(COD_MUNICIPIO) ON UPDATE CASCADE; */
ALTER TABLE ALUNOS DROP CONSTRAINT FK_MUN_NASC;
CONNECT 'C:\Anglo\ANGLO_2005.GDB' USER 'SYSDBA' PASSWORD 'abc';
/* Drop Fields on Table... */
ALTER TABLE ALUNOS DROP UF_NACIONALIDADE_BRASIL;
ALTER TABLE ALUNOS DROP MUNICIPIO_NASC;
ALTER TABLE ALUNOS DROP UF_CARTORIO;
ALTER TABLE ALUNOS DROP NOME_DO_CARTORIO;

/* -- Table: LOGADOURO Field: NOME_LOGADOURO [Type difference] >
 Master: VARCHAR(20)
 Target: CHAR(20) */

