INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21697, '02-12-2020', 'RONALDO DE FREITAS', '2020-12-02', 10);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21697, '10X324,00  02/12/2020', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21697, 'AUT:800540', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21697, 'RONALDO DE FREITAS ', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21716, '3.350,00 8X 30/11/2020', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21716, '664200', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21716, 'LUIZ HIROKT KATO ', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21723, '3.240,00 10X', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21723, '311865', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21723, 'BRITO/FLAVIA C K J ', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21734, '057636', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21734, '3,350.00 6x 30/11/2020', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21734, 'COFFANI/CECILIA C', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21748, '025222 (290,00)', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21748, '290,00 e 2.950,00 a vista', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21748, '384273 (2.950,00)', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21748, 'REGINALDO A GIACOMETTI', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21765, '02-12-2020', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21765, '10X324,00', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21765, 'AUT:202220', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21765, 'RICARDO NASCIMENTO', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21772, '30-11-2020', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21772, '3240,00 06X 30/11/2020', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21772, '728763', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21772, 'LADEIA ELAINE DA SILVA', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21792, '3240,00 10X  01/12/2020', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21792, 'IGOR CESAR SEVERO', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21792, 'R79114', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21806, '3.350,00 10X', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21806, '751941', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21806, 'ELVIO BOCARIM', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21890, '167122', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21890, '2.160,00 8X 01/12/2020', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21890, 'JOSE CARLOS S DIAS', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21894, '2.160,0 8 x  01/12/2020', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21894, 'Noemir Felipetto', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21894, 'aut. 271901', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21937, '10X 240,00  30/11/2020', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21937, 'ANA PAULA MARQUES ', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21937, 'R61114', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21943, '01/12/2020', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21943, '021548', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21943, '1.000 DINHEIRO 1.160 DÉBI', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21943, 'KARLA CRISTINA BASSO AZUM', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21948, '30/11/2020', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21948, '642854', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21948, '8X 2160,00', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21948, 'ANA PAULA VICENTINI', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21975, 'PAGOU MATERIAL EM DINHEIR', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (21975, 'R$2.160,00', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (22006, '2160,00 08X 30/11/2020', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (22006, '965857', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (22006, 'LUCIA I F S LOPES', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (22013, '2160,00 08X 30/11/2020', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (22013, '661837', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (22013, 'IRANETE V MAGALHAES', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (22017, ' 3.350,00 10x 30/11/2020', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (22017, '930502', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (22017, 'ILDA A P WONDRACEK', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (22059, '1160,00 08X 30/11/2020', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (22059, '694595', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (22059, 'ALICE ESTECHE FERNANDEZ', NULL, NULL, NULL);
INSERT INTO AUTO_CARTAO (ALUNOS, AUTORIZACAO, NOME_TITULAR, DATA_PAGAMENTO, PARCELAS)
                 VALUES (22059, 'DINHEIRO 1000,00', NULL, NULL, NULL);

COMMIT WORK;
