/******************************************************************************/
/****               Generated by IBExpert 17/1/2005 15:46:39               ****/
/******************************************************************************/

SET SQL DIALECT 3;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/

CREATE TABLE CORES (
    CODIGO_COR  INTEGER NOT NULL,
    COR         VARCHAR(9) CHARACTER SET NONE
);





/******************************************************************************/
/****                             Primary Keys                             ****/
/******************************************************************************/

ALTER TABLE CORES ADD CONSTRAINT PK_CORES PRIMARY KEY (CODIGO_COR);


/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/

ALTER TABLE alunos
ADD    COR      INTEGER,
ADD CONSTRAINT FK_CORES FOREIGN KEY (COR) REFERENCES CORES (CODIGO_COR) ON UPDATE CASCADE;

CREATE GENERATOR GEN_CORES;
SET GENERATOR GEN_CORES TO 0;

