/******************************************************************************/
/****         Generated by IBExpert 2018.3.1.1 12/12/2018 12:46:06         ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

CREATE DATABASE '172.16.0.78:/bds/Anglo/Usuarios.gdb'
USER 'SYSDBA' PASSWORD 'plkh%321'
PAGE_SIZE 4096
DEFAULT CHARACTER SET WIN1252 COLLATION WIN1252;



/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE GENERATOR GEN_USUARIO;
SET GENERATOR GEN_USUARIO TO 25;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE PARAMETROS_B (
    CONT_ARQ      INTEGER,
    CONT_REMESSA  INTEGER,
    DATA_REMESSA  DATE
);

CREATE TABLE USUARIOS (
    CODIGO  INTEGER NOT NULL,
    LOGIN   VARCHAR(10) NOT NULL,
    SENHA   VARCHAR(8) NOT NULL
);

INSERT INTO PARAMETROS_B (CONT_ARQ, CONT_REMESSA, DATA_REMESSA) VALUES (2, 208, '2018-12-12');

COMMIT WORK;

INSERT INTO USUARIOS (CODIGO, LOGIN, SENHA) VALUES (2, 'AMANDA', '2106');
INSERT INTO USUARIOS (CODIGO, LOGIN, SENHA) VALUES (3, 'FABIO', '260275');
INSERT INTO USUARIOS (CODIGO, LOGIN, SENHA) VALUES (4, 'ALVARO', '280701');
INSERT INTO USUARIOS (CODIGO, LOGIN, SENHA) VALUES (1, 'DEJANIRA', 'aaa');
INSERT INTO USUARIOS (CODIGO, LOGIN, SENHA) VALUES (6, 'AKIRA', 'ak1973');
INSERT INTO USUARIOS (CODIGO, LOGIN, SENHA) VALUES (7, 'TUTUTA', '171821');
INSERT INTO USUARIOS (CODIGO, LOGIN, SENHA) VALUES (15, 'MARCOS', 'mom789');
INSERT INTO USUARIOS (CODIGO, LOGIN, SENHA) VALUES (9, 'FRANCE', 'abc123');
INSERT INTO USUARIOS (CODIGO, LOGIN, SENHA) VALUES (11, 'GISLAINE', 'gis0102');
INSERT INTO USUARIOS (CODIGO, LOGIN, SENHA) VALUES (21, 'VIVI', 'vivi');
INSERT INTO USUARIOS (CODIGO, LOGIN, SENHA) VALUES (22, 'FABIO', 'fabio');
INSERT INTO USUARIOS (CODIGO, LOGIN, SENHA) VALUES (23, 'FLAVIA', 'fla789');
INSERT INTO USUARIOS (CODIGO, LOGIN, SENHA) VALUES (25, 'RIVANIA', 'est123');

COMMIT WORK;



/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE USUARIOS ADD CONSTRAINT PK_USUARIOS PRIMARY KEY (CODIGO);
